const dataset = [
  "Diabetes produces  to urinate or pee a lot, to be thirsty, to lose weight without trying to be very hungry, have blurry vision, feel very tired, and to have very dry skin.",
  "Migraine produces nausea, vomit, headaches and have extreme sensitivity to light and sound.",
  "Bronchitis produces coughing, soreness in the chest, fatigue, headaches, and sore throat.",
  "Influenza (flue) produces fever, headaches fatigue and cough.",
  "Conjunctivitis produces itching, redness, tearing, burning sensation, pus-like discharge and/or crusting of the eyelids.",
  "Gastroenteritis produces diarrhea, nausea, vomiting, headaches, fever, chills, and abdominal pain.",
  "Hypertension produces headaches, shortness of breath, nosebleeds, and severe headaches.",
  "Pneumonia produces coughing, fever, shaking chills, shortness of breath, and chest pain.",
  "Sinusitis produces headaches, a runny nose, pain in the face, and a sore throat.",
  "Tonsillitis produces a sore throat, difficulty swallowing, fever, and swollen glands in the neck.",
  "Asthma produces coughing, wheezing, shortness of breath, and chest tightness.",
  "Mononucleosis produces fatigue, nap frequently, fever, loss of appetite, muscle aches, sore throat and swollen lymph glands and spleen.",
  "Tuberculosis produces coughing, chest pain, coughing up blood, fatigue, fever, night sweats, and chills.",
  "Hepatitis produces the inflammation of the liver, fever, fatigue, nausea, abdominal pain, dark urine, joint pain and loss of appetite.",
  "Chickenpox produces fever, headache, tiredness, and a red rash.",
  "Meningitis produces fever, cold hands and feet, vomit, confusion, pale skin, muscle and joint pain.",
  "Measles produces fever, dry cough, runny nose, sore throat, inflamed eyes, and a skin rash.",
  "Mumps produces fever, headache, tiredness, and swollen salivary glands under the ears.",
  "Rubella produces fever, headache, tiredness, and a pink rash.",
  "Labyrinthitis produces ear pain, nausea, fever, blurred vision, headaches, pressure inside ears, fluid or pus leaking out of the ears.",
  "Pregnancy produces breast changes, fatigue, missed period, nausea and vomiting, food cravings, backache.",
];

module.exports = { dataset };
